apiVersion: apps/v1
kind: Deployment
metadata:
  name: k-monitor
  labels:
    app: k-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k-monitor
  template:
    metadata:
      labels:
        app: k-monitor
    spec:
      serviceAccountName: k-monitor
      terminationGracePeriodSeconds: 60
      containers:
      - name: k-monitor
        image: k-monitor:latest
        imagePullPolicy: Never
        ports:
        - name: api
          containerPort: 80
          protocol: TCP
        - name: frontend
          containerPort: 3000
          protocol: TCP
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 5"]
        startupProbe:
          httpGet:
            path: /api/metrics
            port: 80
          failureThreshold: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/metrics
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /api/metrics
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: k-monitor
spec:
  type: NodePort
  selector:
    app: k-monitor
  ports:
  - name: api
    port: 80
    targetPort: 80
    protocol: TCP
  - name: frontend
    port: 3000
    targetPort: 3000
    protocol: TCP 