apiVersion: apps/v1
kind: Deployment
metadata:
  name: k-monitor
  namespace: default
  labels:
    app: k-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k-monitor
  template:
    metadata:
      labels:
        app: k-monitor
    spec:
      serviceAccountName: k-monitor
      containers:
      - name: k-monitor
        image: k-monitor:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
        - containerPort: 8080
          name: api
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
---

apiVersion: v1
kind: Service
metadata:
  name: k-monitor
spec:
  type: NodePort  # Changed from LoadBalancer to NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080  # Explicitly set the node port
    protocol: TCP
    name: http
  selector:
    app: k-monitor 