apiVersion: apps/v1
kind: Deployment
metadata:
  name: k-monitor
  labels:
    app: k-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k-monitor
  template:
    metadata:
      labels:
        app: k-monitor
    spec:
      serviceAccountName: k-monitor
      terminationGracePeriodSeconds: 60
      containers:
      - name: k-monitor
        image: k-monitor:latest
        imagePullPolicy: Never
        ports:
        - name: web
          containerPort: 8080
          protocol: TCP
        - name: frontend
          containerPort: 3000
          protocol: TCP
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 5"]
        startupProbe:
          httpGet:
            path: /api/metrics
            port: 8080
          failureThreshold: 30
          periodSeconds: 30
          timeoutSeconds: 10  # Ensure this matches Go service response time
        readinessProbe:
          httpGet:
            path: /api/metrics
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /api/metrics
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 15
          failureThreshold: 5
---

apiVersion: v1
kind: Service
metadata:
  name: k-monitor
spec:
  type: NodePort
  selector:
    app: k-monitor
  ports:
  - name: web
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: frontend
    port: 3000
    targetPort: 3000
    protocol: TCP 